global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-prometheus-grafana'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080',]
      - targets: ['host.docker.internal:300']
      - targets: ['host.docker.internal:8080']
      - targets: ['host.docker.internal:8080']
















# docker compose up -d

# http://localhost:9090
# http://prometheus:9090 for Grafana Url
# https://grafana.com/grafana/dashboards/4701-jvm-micrometer/
# https://grafana.com/grafana/dashboards/17053-spring-boot-statistics-endpoint-metrics/
